name: PR checks

on: pull_request

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/backend
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
        with:
          version: "0.12.13"
      - run: cp .env.example .env
      - run: uv sync --frozen
      - run: uv build
      - run: docker build .
      - run: uv run ruff check
      - run: uv run ruff format --check
      - run: uv run mypy
      - run: uv run pytest

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/frontend
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: packages/frontend/.nvmrc
          cache: npm
          cache-dependency-path: packages/frontend/package-lock.json
      - run: npm ci
      - run: npm run build
      - run: docker build --target runtime .
      - run: npm run check
      - run: npm test
